import { Department,OrganizationMember,Project,Task } from "@/src/app/(admin)/admin/types"

export type DepartmentMember = {
  id: number
  name: string
  position: string
  salary: number
  experience: number
  joinDate: string
  email: string
  phone: string
  address: string
  manager: string
  skills: string[]
  performance: number
  avatar?: string
}

export const sampleMembers: OrganizationMember[] = [
  // IT Development Department
  {
    id: 1,
    name: "Sarah Johnson",
    role: "Head",
    department: "IT Development",
    salary: 120000,
    projects: ["E-commerce Platform Redesign", "Mobile Banking App", "Cloud Migration"],
    experience: 10,
    contactInfo: {
      email: "sarah.johnson@oneaimit.com",
      phone: "+1-555-0100",
      address: "100 Tech Street, Silicon Valley",
    },
    documents: {
      pan: "ABCDE0000A",
      aadhar: "1000-0000-0000",
    },
    joiningDate: "2020-01-15",
    performanceMetrics: {
      tasksPerDay: 5.2,
      attendanceScore: 98,
      managerReviewRating: 4.9,
      combinedPercentage: 96,
    },
    attendance: {
      last7Days: [true, true, true, true, true, true, false],
      todayPresent: true,
    },
  },
  {
    id: 2,
    name: "John Doe",
    role: "Manager",
    department: "IT Development",
    salary: 85000,
    projects: ["E-commerce Platform Redesign", "Mobile Banking App"],
    experience: 5,
    contactInfo: {
      email: "john.doe@oneaimit.com",
      phone: "+1-555-0101",
      address: "123 Tech Street, Silicon Valley",
    },
    documents: {
      pan: "ABCDE1234F",
      aadhar: "1234-5678-9012",
    },
    joiningDate: "2023-01-15",
    performanceMetrics: {
      tasksPerDay: 4.2,
      attendanceScore: 95,
      managerReviewRating: 4.5,
      combinedPercentage: 92,
    },
    attendance: {
      last7Days: [true, true, true, false, true, true, true],
      todayPresent: true,
    },
    upperManagerName: "Sarah Johnson",
  },
  {
    id: 3,
    name: "Jane Smith",
    role: "Employee",
    department: "IT Development",
    salary: 65000,
    projects: ["E-commerce Platform Redesign"],
    experience: 3,
    contactInfo: {
      email: "jane.smith@oneaimit.com",
      phone: "+1-555-0102",
      address: "456 Code Avenue, Tech City",
    },
    documents: {
      pan: "FGHIJ5678K",
      aadhar: "2345-6789-0123",
    },
    joiningDate: "2023-03-20",
    performanceMetrics: {
      tasksPerDay: 3.8,
      attendanceScore: 88,
      managerReviewRating: 4.2,
      combinedPercentage: 88,
    },
    attendance: {
      last7Days: [true, true, false, true, true, true, true],
      todayPresent: true,
    },
    upperManagerName: "John Doe",
  },
  {
    id: 4,
    name: "Alex Chen",
    role: "Employee",
    department: "IT Development",
    salary: 72000,
    projects: ["Mobile Banking App", "Inventory Management System"],
    experience: 4,
    contactInfo: {
      email: "alex.chen@oneaimit.com",
      phone: "+1-555-0103",
      address: "789 Developer Drive, Code Valley",
    },
    documents: {
      pan: "LMNOP9012Q",
      aadhar: "3456-7890-1234",
    },
    joiningDate: "2022-08-10",
    performanceMetrics: {
      tasksPerDay: 4.1,
      attendanceScore: 92,
      managerReviewRating: 4.4,
      combinedPercentage: 90,
    },
    attendance: {
      last7Days: [true, true, true, true, false, true, true],
      todayPresent: true,
    },
    upperManagerName: "John Doe",
  },
  {
    id: 5,
    name: "Mike Johnson",
    role: "Employee",
    department: "IT Development",
    salary: 68000,
    projects: ["E-commerce Platform Redesign", "Healthcare Portal"],
    experience: 3,
    contactInfo: {
      email: "mike.johnson@oneaimit.com",
      phone: "+1-555-0104",
      address: "321 Code Street, Dev City",
    },
    documents: {
      pan: "RSTUV3456W",
      aadhar: "4567-8901-2345",
    },
    joiningDate: "2023-06-01",
    performanceMetrics: {
      tasksPerDay: 3.9,
      attendanceScore: 89,
      managerReviewRating: 4.3,
      combinedPercentage: 87,
    },
    attendance: {
      last7Days: [true, false, true, true, true, true, true],
      todayPresent: true,
    },
    upperManagerName: "John Doe",
  },
  {
    id: 6,
    name: "Lisa Wang",
    role: "Intern",
    department: "IT Development",
    salary: 35000,
    projects: ["Learning Management System"],
    experience: 0.5,
    contactInfo: {
      email: "lisa.wang@oneaimit.com",
      phone: "+1-555-0105",
      address: "321 Intern Lane, Fresh Valley",
    },
    documents: {
      pan: "WXYZAB7890",
      aadhar: "5678-9012-3456",
    },
    joiningDate: "2024-08-01",
    performanceMetrics: {
      tasksPerDay: 2.5,
      attendanceScore: 85,
      managerReviewRating: 3.8,
      combinedPercentage: 78,
    },
    attendance: {
      last7Days: [true, false, true, true, true, true, true],
      todayPresent: true,
    },
    upperManagerName: "Jane Smith",
  },

  // HR Department
  {
    id: 7,
    name: "David Brown",
    role: "Head",
    department: "HR",
    salary: 95000,
    projects: ["HR Management System", "Employee Wellness Program"],
    experience: 8,
    contactInfo: {
      email: "david.brown@oneaimit.com",
      phone: "+1-555-0200",
      address: "200 People Street, HR Heights",
    },
    documents: {
      pan: "CDEFGH4567",
      aadhar: "6789-0123-4567",
    },
    joiningDate: "2021-05-15",
    performanceMetrics: {
      tasksPerDay: 4.8,
      attendanceScore: 97,
      managerReviewRating: 4.7,
      combinedPercentage: 94,
    },
    attendance: {
      last7Days: [true, true, true, true, true, false, true],
      todayPresent: true,
    },
  },
  {
    id: 8,
    name: "Sarah Wilson",
    role: "Manager",
    department: "HR",
    salary: 70000,
    projects: ["HR Management System"],
    experience: 6,
    contactInfo: {
      email: "sarah.wilson@oneaimit.com",
      phone: "+1-555-0201",
      address: "321 People Street, HR Heights",
    },
    documents: {
      pan: "KLMNO9012P",
      aadhar: "3456-7890-1234",
    },
    joiningDate: "2022-11-05",
    performanceMetrics: {
      tasksPerDay: 4.5,
      attendanceScore: 98,
      managerReviewRating: 4.8,
      combinedPercentage: 94,
    },
    attendance: {
      last7Days: [true, true, true, true, true, true, false],
      todayPresent: true,
    },
    upperManagerName: "David Brown",
  },
  {
    id: 9,
    name: "Michael Rodriguez",
    role: "Employee",
    department: "HR",
    salary: 58000,
    projects: ["Employee Wellness Program", "Recruitment Portal"],
    experience: 3,
    contactInfo: {
      email: "michael.rodriguez@oneaimit.com",
      phone: "+1-555-0202",
      address: "654 Talent Avenue, Recruitment Row",
    },
    documents: {
      pan: "IJKLMN8901",
      aadhar: "7890-1234-5678",
    },
    joiningDate: "2023-02-20",
    performanceMetrics: {
      tasksPerDay: 3.9,
      attendanceScore: 91,
      managerReviewRating: 4.1,
      combinedPercentage: 87,
    },
    attendance: {
      last7Days: [true, true, true, false, true, true, true],
      todayPresent: true,
    },
    upperManagerName: "Sarah Wilson",
  },
  {
    id: 10,
    name: "Jennifer Lee",
    role: "Employee",
    department: "HR",
    salary: 62000,
    projects: ["Performance Management System"],
    experience: 4,
    contactInfo: {
      email: "jennifer.lee@oneaimit.com",
      phone: "+1-555-0203",
      address: "987 Performance Plaza, Review Ridge",
    },
    documents: {
      pan: "OPQRST2345",
      aadhar: "8901-2345-6789",
    },
    joiningDate: "2022-06-15",
    performanceMetrics: {
      tasksPerDay: 4.3,
      attendanceScore: 94,
      managerReviewRating: 4.6,
      combinedPercentage: 91,
    },
    attendance: {
      last7Days: [true, true, true, true, true, true, true],
      todayPresent: true,
    },
    upperManagerName: "Sarah Wilson",
  },

  // Business Development Department
  {
    id: 11,
    name: "Maria Garcia",
    role: "Head",
    department: "Business Development",
    salary: 110000,
    projects: ["Market Analysis Dashboard", "Client Acquisition Platform", "Sales Analytics"],
    experience: 9,
    contactInfo: {
      email: "maria.garcia@oneaimit.com",
      phone: "+1-555-0300",
      address: "300 Business Blvd, Commerce Center",
    },
    documents: {
      pan: "UVWXYZ6789",
      aadhar: "9012-3456-7890",
    },
    joiningDate: "2020-09-10",
    performanceMetrics: {
      tasksPerDay: 5.1,
      attendanceScore: 96,
      managerReviewRating: 4.8,
      combinedPercentage: 95,
    },
    attendance: {
      last7Days: [true, true, true, true, true, true, true],
      todayPresent: true,
    },
  },
  {
    id: 12,
    name: "Robert Thompson",
    role: "Manager",
    department: "Business Development",
    salary: 78000,
    projects: ["Client Acquisition Platform", "Partnership Portal"],
    experience: 5,
    contactInfo: {
      email: "robert.thompson@oneaimit.com",
      phone: "+1-555-0301",
      address: "456 Sales Street, Deal District",
    },
    documents: {
      pan: "ABCDEF0123",
      aadhar: "0123-4567-8901",
    },
    joiningDate: "2022-03-15",
    performanceMetrics: {
      tasksPerDay: 4.4,
      attendanceScore: 93,
      managerReviewRating: 4.5,
      combinedPercentage: 89,
    },
    attendance: {
      last7Days: [true, true, false, true, true, true, true],
      todayPresent: true,
    },
    upperManagerName: "Maria Garcia",
  },
  {
    id: 13,
    name: "Emma Davis",
    role: "Employee",
    department: "Business Development",
    salary: 68000,
    projects: ["Market Analysis Dashboard"],
    experience: 4,
    contactInfo: {
      email: "emma.davis@oneaimit.com",
      phone: "+1-555-0302",
      address: "654 Business Blvd, Commerce Center",
    },
    documents: {
      pan: "QRSTU3456V",
      aadhar: "4567-8901-2345",
    },
    joiningDate: "2023-01-20",
    performanceMetrics: {
      tasksPerDay: 4.0,
      attendanceScore: 92,
      managerReviewRating: 4.3,
      combinedPercentage: 86,
    },
    attendance: {
      last7Days: [true, false, true, true, true, true, true],
      todayPresent: false,
    },
    upperManagerName: "Robert Thompson",
  },
  {
    id: 14,
    name: "Kevin Park",
    role: "Employee",
    department: "Business Development",
    salary: 71000,
    projects: ["Sales Analytics", "CRM Integration"],
    experience: 3,
    contactInfo: {
      email: "kevin.park@oneaimit.com",
      phone: "+1-555-0303",
      address: "789 Revenue Road, Profit Point",
    },
    documents: {
      pan: "GHIJKL4567",
      aadhar: "1234-5678-9012",
    },
    joiningDate: "2023-07-10",
    performanceMetrics: {
      tasksPerDay: 3.7,
      attendanceScore: 89,
      managerReviewRating: 4.2,
      combinedPercentage: 85,
    },
    attendance: {
      last7Days: [true, true, true, true, false, true, true],
      todayPresent: true,
    },
    upperManagerName: "Robert Thompson",
  },

  // IT/CS Department
  {
    id: 15,
    name: "Robert Chen",
    role: "Head",
    department: "IT/CS",
    salary: 115000,
    projects: ["Infrastructure Modernization", "Security Audit", "Network Optimization"],
    experience: 12,
    contactInfo: {
      email: "robert.chen@oneaimit.com",
      phone: "+1-555-0400",
      address: "400 Infrastructure Ave, System City",
    },
    documents: {
      pan: "MNOPQR8901",
      aadhar: "2345-6789-0123",
    },
    joiningDate: "2019-04-20",
    performanceMetrics: {
      tasksPerDay: 5.3,
      attendanceScore: 99,
      managerReviewRating: 4.9,
      combinedPercentage: 97,
    },
    attendance: {
      last7Days: [true, true, true, true, true, true, true],
      todayPresent: true,
    },
  },
  {
    id: 16,
    name: "Amanda Foster",
    role: "Manager",
    department: "IT/CS",
    salary: 82000,
    projects: ["Security Audit", "Backup Systems"],
    experience: 6,
    contactInfo: {
      email: "amanda.foster@oneaimit.com",
      phone: "+1-555-0401",
      address: "567 Security Street, Safe Harbor",
    },
    documents: {
      pan: "STUVWX2345",
      aadhar: "3456-7890-1234",
    },
    joiningDate: "2021-11-30",
    performanceMetrics: {
      tasksPerDay: 4.6,
      attendanceScore: 95,
      managerReviewRating: 4.7,
      combinedPercentage: 93,
    },
    attendance: {
      last7Days: [true, true, true, true, true, false, true],
      todayPresent: true,
    },
    upperManagerName: "Robert Chen",
  },
  {
    id: 17,
    name: "Daniel Kim",
    role: "Employee",
    department: "IT/CS",
    salary: 74000,
    projects: ["Network Optimization", "Server Maintenance"],
    experience: 4,
    contactInfo: {
      email: "daniel.kim@oneaimit.com",
      phone: "+1-555-0402",
      address: "890 Network Lane, Connection Court",
    },
    documents: {
      pan: "YZABCD6789",
      aadhar: "4567-8901-2345",
    },
    joiningDate: "2022-01-25",
    performanceMetrics: {
      tasksPerDay: 4.2,
      attendanceScore: 91,
      managerReviewRating: 4.4,
      combinedPercentage: 88,
    },
    attendance: {
      last7Days: [true, true, false, true, true, true, true],
      todayPresent: true,
    },
    upperManagerName: "Amanda Foster",
  },
  {
    id: 18,
    name: "Rachel Green",
    role: "Employee",
    department: "IT/CS",
    salary: 69000,
    projects: ["Infrastructure Modernization", "Cloud Security"],
    experience: 3,
    contactInfo: {
      email: "rachel.green@oneaimit.com",
      phone: "+1-555-0403",
      address: "123 Cloud Avenue, Virtual Valley",
    },
    documents: {
      pan: "EFGHIJ0123",
      aadhar: "5678-9012-3456",
    },
    joiningDate: "2023-05-15",
    performanceMetrics: {
      tasksPerDay: 3.9,
      attendanceScore: 87,
      managerReviewRating: 4.1,
      combinedPercentage: 84,
    },
    attendance: {
      last7Days: [true, true, true, false, true, true, true],
      todayPresent: true,
    },
    upperManagerName: "Amanda Foster",
  },

  // Management Department
  {
    id: 19,
    name: "William Anderson",
    role: "Head",
    department: "Management",
    salary: 150000,
    projects: ["Strategic Planning 2024", "Digital Transformation", "Organizational Restructure"],
    experience: 15,
    contactInfo: {
      email: "william.anderson@oneaimit.com",
      phone: "+1-555-0500",
      address: "500 Executive Plaza, Leadership Lane",
    },
    documents: {
      pan: "KLMNOP4567",
      aadhar: "6789-0123-4567",
    },
    joiningDate: "2018-01-10",
    performanceMetrics: {
      tasksPerDay: 6.2,
      attendanceScore: 98,
      managerReviewRating: 4.9,
      combinedPercentage: 98,
    },
    attendance: {
      last7Days: [true, true, true, true, true, true, false],
      todayPresent: true,
    },
  },
  {
    id: 20,
    name: "Patricia Miller",
    role: "Manager",
    department: "Management",
    salary: 95000,
    projects: ["Digital Transformation", "Process Optimization"],
    experience: 8,
    contactInfo: {
      email: "patricia.miller@oneaimit.com",
      phone: "+1-555-0501",
      address: "678 Strategy Street, Vision Valley",
    },
    documents: {
      pan: "QRSTUV8901",
      aadhar: "7890-1234-5678",
    },
    joiningDate: "2020-06-20",
    performanceMetrics: {
      tasksPerDay: 5.1,
      attendanceScore: 96,
      managerReviewRating: 4.6,
      combinedPercentage: 94,
    },
    attendance: {
      last7Days: [true, true, true, true, true, true, true],
      todayPresent: true,
    },
    upperManagerName: "William Anderson",
  },
  {
    id: 21,
    name: "James Wilson",
    role: "Manager",
    department: "Management",
    salary: 88000,
    projects: ["Organizational Restructure", "Performance Analytics"],
    experience: 7,
    contactInfo: {
      email: "james.wilson@oneaimit.com",
      phone: "+1-555-0502",
      address: "345 Operations Blvd, Efficiency Estate",
    },
    documents: {
      pan: "WXYZAB0123",
      aadhar: "8901-2345-6789",
    },
    joiningDate: "2021-03-15",
    performanceMetrics: {
      tasksPerDay: 4.8,
      attendanceScore: 94,
      managerReviewRating: 4.5,
      combinedPercentage: 92,
    },
    attendance: {
      last7Days: [true, true, false, true, true, true, true],
      todayPresent: true,
    },
    upperManagerName: "William Anderson",
  },
]
export const sampleDepartments: Department[] = [
  {
    id: 1,
    name: "IT Development",
    head: "Sarah Johnson",
    budget: 850000,
    managers: sampleMembers.filter((m) => m.role === "Manager" && m.department === "IT Development"),
    employees: sampleMembers.filter((m) => m.role === "Employee" && m.department === "IT Development"),
    interns: sampleMembers.filter((m) => m.role === "Intern" && m.department === "IT Development"),
    members: sampleMembers.filter((m) => m.department === "IT Development"),
  },
  {
    id: 2,
    name: "HR",
    head: "David Brown",
    budget: 320000,
    managers: sampleMembers.filter((m) => m.role === "Manager" && m.department === "HR"),
    employees: sampleMembers.filter((m) => m.role === "Employee" && m.department === "HR"),
    interns: sampleMembers.filter((m) => m.role === "Intern" && m.department === "HR"),
    members: sampleMembers.filter((m) => m.department === "HR"),
  },
  {
    id: 3,
    name: "Business Development",
    head: "Maria Garcia",
    budget: 420000,
    managers: sampleMembers.filter((m) => m.role === "Manager" && m.department === "Business Development"),
    employees: sampleMembers.filter((m) => m.role === "Employee" && m.department === "Business Development"),
    interns: sampleMembers.filter((m) => m.role === "Intern" && m.department === "Business Development"),
    members: sampleMembers.filter((m) => m.department === "Business Development"),
  },
  {
    id: 4,
    name: "IT/CS",
    head: "Robert Chen",
    budget: 500000,
    managers: sampleMembers.filter((m) => m.role === "Manager" && m.department === "IT/CS"),
    employees: sampleMembers.filter((m) => m.role === "Employee" && m.department === "IT/CS"),
    interns: sampleMembers.filter((m) => m.role === "Intern" && m.department === "IT/CS"),
    members: sampleMembers.filter((m) => m.department === "IT/CS"),
  },
  {
    id: 5,
    name: "Management",
    head: "William Anderson",
    budget: 750000,
    managers: sampleMembers.filter((m) => m.role === "Manager" && m.department === "Management"),
    employees: sampleMembers.filter((m) => m.role === "Employee" && m.department === "Management"),
    interns: sampleMembers.filter((m) => m.role === "Intern" && m.department === "Management"),
    members: sampleMembers.filter((m) => m.department === "Management"),
  },
]
export const sampleProjects: Project[] = [
  {
    id: 1,
    name: "E-commerce Platform Redesign",
    description: "Complete redesign of the existing e-commerce platform with modern UI/UX, improved performance, and mobile responsiveness.",
    departmentsInvolved: ["IT Development", "Business Development"],
    membersInvolved: ["John Doe", "Jane Smith", "Mike Johnson", "Sarah Wilson", "Emma Davis"],
    startDate: "2024-01-15",
    deadline: "2024-06-30",
    managersInvolved: ["John Doe", "Robert Thompson"],
    completionPercentage: 75,
    amount: 150000,
    client: "TechCorp Solutions",
    projectScope:
      "Complete redesign of the existing e-commerce platform with modern UI/UX, improved performance, and mobile responsiveness.",
    clientInputs:
      "Client wants a modern, clean design with focus on user experience and conversion optimization. Must support multiple payment gateways.",
    skillsRequired: ["React", "Node.js", "MongoDB", "AWS", "UI/UX Design"],
    status: "active",
    priority: "High",
    category: "Web Development",
    technologiesUsed: ["React", "Node.js", "MongoDB", "AWS", "Stripe", "PayPal"],
    budgetAllocated: 150000,
    actualSpent: 112500,
    estimatedHours: 1200,
    actualHours: 900,
    riskAssessment: "Medium",
    projectLead: "John Doe",
    milestonesAchieved: ["UI Design Complete", "Backend API Development", "Payment Integration"],
    assignDate: "2024-01-10",
    qualityScore: "85%",
    successRate: "92%",
    costEfficiency: "75%",
    budgetVsActual: "Under budget by 25%",
  },
  {
    id: 2,
    name: "Mobile Banking App",
    description: "Development of a secure mobile banking application with biometric authentication, transaction history, and bill payment features.",
    departmentsInvolved: ["IT Development", "IT/CS"],
    membersInvolved: ["Sarah Johnson", "Alex Chen", "Amanda Foster", "Rachel Green"],
    startDate: "2023-09-01",
    deadline: "2024-02-28",
    managersInvolved: ["Sarah Johnson", "Amanda Foster"],
    completionPercentage: 100,
    amount: 200000,
    client: "First National Bank",
    projectScope:
      "Development of a secure mobile banking application with biometric authentication, transaction history, and bill payment features.",
    clientInputs:
      "High security requirements, must comply with banking regulations, intuitive user interface for all age groups.",
    skillsRequired: ["React Native", "Node.js", "PostgreSQL", "Biometric Auth", "Security"],
    status: "completed",
    showcaseLink: "https://app.firstnationalbank.com",
    effectAnalysis:
      "The mobile app increased customer engagement by 40% and reduced branch visits by 60%. Customer satisfaction scores improved from 3.2 to 4.6 out of 5.",
    priority: "High",
    category: "Mobile Development",
    technologiesUsed: ["React Native", "Node.js", "PostgreSQL", "TouchID", "FaceID", "AWS"],
    clientSatisfaction: "5",
    roi: 180,
    budgetAllocated: 200000,
    actualSpent: 195000,
    estimatedHours: 1600,
    actualHours: 1580,
    riskAssessment: "High",
    projectLead: "Sarah Johnson",
    milestonesAchieved: ["Security Framework", "Core Features", "Testing Complete", "App Store Approval"],
    lessonsLearned:
      "Early security testing is crucial for banking applications. Regular client feedback sessions helped avoid major revisions.",
    clientFeedback: "Exceptional work! The app exceeded our expectations and our customers love the new features.",
    assignDate: "2023-08-25",
    qualityScore: "95%",
    successRate: "100%",
    costEfficiency: "97.5%",
    budgetVsActual: "Under budget by 2.5%",
  },
  {
    id: 3,
    name: "Inventory Management System",
    description: "Custom inventory management system with real-time tracking, automated reordering, and comprehensive reporting.",
    departmentsInvolved: ["IT Development", "Business Development"],
    membersInvolved: ["Alex Chen", "Maria Garcia", "Kevin Park"],
    startDate: "2024-03-01",
    deadline: "2024-08-15",
    managersInvolved: ["John Doe", "Robert Thompson"],
    completionPercentage: 45,
    amount: 80000,
    client: "Warehouse Solutions Inc",
    projectScope:
      "Custom inventory management system with real-time tracking, automated reordering, and comprehensive reporting.",
    clientInputs: "Need integration with existing ERP system, barcode scanning capability, and multi-location support.",
    skillsRequired: ["Python", "Django", "PostgreSQL", "React", "Barcode Integration"],
    status: "active",
    priority: "Medium",
    category: "Enterprise Software",
    technologiesUsed: ["Python", "Django", "PostgreSQL", "React", "Redis"],
    budgetAllocated: 80000,
    actualSpent: 36000,
    estimatedHours: 800,
    actualHours: 360,
    riskAssessment: "Low",
    projectLead: "John Doe",
    milestonesAchieved: ["Database Design", "Core API Development"],
    assignDate: "2024-02-25",
    qualityScore: "78%",
    successRate: "85%",
    costEfficiency: "90%",
    budgetVsActual: "On track",
  },
  {
    id: 4,
    name: "Healthcare Portal",
    description: "HIPAA-compliant patient portal with appointment scheduling, medical records access, and telemedicine capabilities.",
    departmentsInvolved: ["IT Development", "IT/CS"],
    membersInvolved: ["Mike Johnson", "Daniel Kim", "Rachel Green", "Amanda Foster"],
    startDate: "2023-06-01",
    deadline: "2023-12-31",
    managersInvolved: ["Sarah Johnson", "Amanda Foster"],
    completionPercentage: 100,
    amount: 300000,
    client: "Regional Medical Center",
    projectScope:
      "HIPAA-compliant patient portal with appointment scheduling, medical records access, and telemedicine capabilities.",
    clientInputs: "Must be HIPAA compliant, integrate with existing EMR system, support video consultations.",
    skillsRequired: ["React", "Node.js", "HIPAA Compliance", "WebRTC", "MySQL"],
    status: "completed",
    showcaseLink: "https://portal.regionalmedical.com",
    effectAnalysis:
      "Reduced administrative workload by 35%, improved patient satisfaction by 50%, and enabled 200+ virtual consultations per month.",
    priority: "High",
    category: "Healthcare",
    technologiesUsed: ["React", "Node.js", "MySQL", "WebRTC", "AWS HIPAA", "Twilio"],
    clientSatisfaction: "4",
    roi: 220,
    budgetAllocated: 300000,
    actualSpent: 285000,
    estimatedHours: 2000,
    actualHours: 1900,
    riskAssessment: "High",
    projectLead: "Sarah Johnson",
    milestonesAchieved: ["HIPAA Compliance Review", "EMR Integration", "Telemedicine Features", "Security Audit"],
    lessonsLearned:
      "Healthcare projects require extensive compliance documentation. Early involvement of legal team is essential.",
    clientFeedback: "Great technical execution and attention to compliance requirements.",
    assignDate: "2023-05-25",
    qualityScore: "88%",
    successRate: "95%",
    costEfficiency: "95%",
    budgetVsActual: "Under budget by 5%",
  },
  {
    id: 5,
    name: "Learning Management System",
    description: "Comprehensive LMS with course management, student tracking, assignment submission, and grading system.",
    departmentsInvolved: ["IT Development", "HR"],
    membersInvolved: ["Lisa Wang", "Jennifer Lee", "Michael Rodriguez"],
    startDate: "2024-02-01",
    deadline: "2024-09-30",
    managersInvolved: ["Sarah Wilson"],
    completionPercentage: 30,
    amount: 120000,
    client: "State University",
    projectScope:
      "Comprehensive LMS with course management, student tracking, assignment submission, and grading system.",
    clientInputs:
      "Must support 10,000+ concurrent users, integrate with existing student information system, mobile-friendly design.",
    skillsRequired: ["Vue.js", "Laravel", "MySQL", "Redis", "Mobile Design"],
    status: "pending",
    priority: "Medium",
    category: "Education",
    technologiesUsed: ["Vue.js", "Laravel", "MySQL", "Redis", "AWS"],
    budgetAllocated: 120000,
    actualSpent: 36000,
    estimatedHours: 1000,
    actualHours: 300,
    riskAssessment: "Medium",
    projectLead: "Sarah Wilson",
    milestonesAchieved: ["Requirements Analysis", "System Architecture"],
    assignDate: "2024-01-25",
    qualityScore: "70%",
    successRate: "80%",
    costEfficiency: "85%",
    budgetVsActual: "On track",
  },
  {
    id: 6,
    name: "HR Management System",
    description: "Internal HR management system for employee tracking and performance management.",
    departmentsInvolved: ["HR", "IT Development"],
    membersInvolved: ["Sarah Wilson", "John Doe", "Michael Rodriguez"],
    startDate: "2024-03-15",
    deadline: "2024-07-20",
    managersInvolved: ["Sarah Wilson", "John Doe"],
    completionPercentage: 80,
    amount: 120000,
    client: "Internal Project",
    projectScope: "Internal HR management system for employee tracking and performance",
    clientInputs: "Employee database, performance tracking, attendance management",
    skillsRequired: ["React", "Python", "PostgreSQL"],
    effectAnalysis: "50% reduction in HR administrative tasks",
    status: "active",
    priority: "High",
    category: "Internal Systems",
    technologiesUsed: ["React", "Python", "PostgreSQL", "Redis"],
    budgetAllocated: 120000,
    actualSpent: 96000,
    estimatedHours: 960,
    actualHours: 768,
    riskAssessment: "Low",
    projectLead: "Sarah Wilson",
    milestonesAchieved: ["Database Design", "Core Features", "Testing Phase"],
    assignDate: "2023-11-15",
    qualityScore: "90%",
    successRate: "93%",
    costEfficiency: "80%",
    budgetVsActual: "Over budget by 20%",
  },
  {
    id: 7,
    name: "Infrastructure Modernization",
    description: "Modernize IT infrastructure with cloud migration and security enhancements.",
    departmentsInvolved: ["IT/CS", "Management"],
    membersInvolved: ["Robert Chen", "Amanda Foster", "Daniel Kim", "Patricia Miller"],
    startDate: "2024-02-01",
    deadline: "2024-09-30",
    managersInvolved: ["Robert Chen", "Amanda Foster", "Patricia Miller"],
    completionPercentage: 45,
    amount: 180000,
    client: "Internal Project",
    projectScope: "Modernize IT infrastructure with cloud migration and security enhancements",
    clientInputs: "Cloud-first approach, enhanced security, scalable architecture",
    skillsRequired: ["AWS", "Docker", "Kubernetes", "Terraform"],
    effectAnalysis: "60% improvement in system performance and 40% cost reduction",
    status: "active",
    priority: "High",
    category: "Infrastructure",
    technologiesUsed: ["AWS", "Docker", "Kubernetes", "Terraform", "Ansible"],
    budgetAllocated: 180000,
    actualSpent: 81000,
    estimatedHours: 1440,
    actualHours: 648,
    riskAssessment: "Medium",
    projectLead: "Robert Chen",
    milestonesAchieved: ["Cloud Architecture Design", "Security Framework"],
    assignDate: "2024-04-01",
    qualityScore: "82%",
    successRate: "88%",
    costEfficiency: "90%",
    budgetVsActual: "Under budget by 55%",
  },
]
export const sampleTasks: Task[] = [
  // IT Development Tasks
  {
    _id: 1,
    title: "Complete API Documentation",
    description: "Document all REST API endpoints for the e-commerce platform",
    assignedTo: { id: "2", name: "Jane Smith" },
    assignedBy: { id: "1", name: "John Doe" },
    dueDate: "2024-02-15",
    status: "in-progress",
    priority: "high",
    project: "E-commerce Platform Redesign",
  },
  {
    _id: 2,
    title: "Implement Payment Gateway",
    description: "Integrate Stripe payment gateway with the e-commerce platform",
    assignedTo: { id: "4", name: "Alex Chen" },
    assignedBy: { id: "3", name: "Sarah Johnson" },
    dueDate: "2024-02-20",
    status: "pending",
    priority: "urgent",
    project: "E-commerce Platform Redesign",
  },
]

export const sampleOngoingProjects: Project[] = [
  {
    id: 1,
    name: "E-commerce Platform Redesign",
    description: "Complete overhaul of the existing e-commerce platform with modern UI/UX and enhanced functionality.",
    departmentsInvolved: ["IT Development", "Business Development"],
    membersInvolved: ["John Doe", "Jane Smith", "Mike Johnson"],
    startDate: "2024-01-10",
    deadline: "2024-08-15",
    managersInvolved: ["John Doe"],
    completionPercentage: 65,
    amount: 250000,
    client: "TechCorp Solutions",
    projectScope: "Complete overhaul of the existing e-commerce platform with modern UI/UX and enhanced functionality.",
    clientInputs: "Modern UI/UX design with focus on user experience and mobile responsiveness.",
    skillsRequired: ["React", "Node.js", "MongoDB", "AWS"],
    status: "active",
    priority: "High",
    category: "Web Development",
    technologiesUsed: ["React", "Node.js", "MongoDB", "AWS"],
    budgetAllocated: 250000,
    actualSpent: 162500,
    estimatedHours: 2000,
    actualHours: 1300,
    riskAssessment: "Medium",
    projectLead: "John Doe",
    milestonesAchieved: ["UI Design Complete", "Backend API Development"],
    qualityScore: "",
    successRate: "",
    costEfficiency: "",
    budgetVsActual: ""
  },
  {
    id: 2,
    name: "Mobile Banking App",
    description: "Development of a secure mobile banking application with biometric authentication.",
    departmentsInvolved: ["IT Development", "IT/CS"],
    membersInvolved: ["Jane Smith", "Emma Davis"],
    startDate: "2024-02-01",
    deadline: "2024-09-30",
    managersInvolved: ["Sarah Johnson"],
    completionPercentage: 40,
    amount: 180000,
    client: "SecureBank Ltd",
    projectScope: "Development of a secure mobile banking application with biometric authentication.",
    clientInputs: "High security requirements with biometric authentication and compliance with banking regulations.",
    skillsRequired: ["React Native", "Node.js", "Security", "Biometric Auth"],
    status: "active",
    priority: "High",
    category: "Mobile Development",
    technologiesUsed: ["React Native", "Node.js", "PostgreSQL"],
    budgetAllocated: 180000,
    actualSpent: 72000,
    estimatedHours: 1500,
    actualHours: 600,
    riskAssessment: "High",
    projectLead: "Sarah Johnson",
    milestonesAchieved: ["Security Framework", "Core Features Planning"],
    qualityScore: "",
    successRate: "",
    costEfficiency: "",
    budgetVsActual: ""
  },
]
